sudo: false
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

env:
  global:
    - PACKAGE_NAME=ctwavelet

before_install:
  - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION

script:
  - python setup.py sdist bdist_wheel
  - pip install .
  - pip install pytest
  - pip install codecov
  - pytest tests/*
  - codecov

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: TY2nnirLmg223ldugBKnduhuIbA8SAlcKvxuWZm5w68SRi+KBCoO3U8jxG4vW89S7SICbOn02rW3OqypzwYjhFQNc0/pUJ5bDX0QnbABmU0ViaukRbO2hlZ93dG/m2H4zAPkebXe9jFgW1HQMUPvZEkS/o1hSNpcxO+pjcESzyORMOTgo29ivQsz65eH4m42OZtPCLMqCHl5Ti9v/LcxpZ7rBOo4i+wX/1VoaYdozZh0mpewpJ9nmJP7r9dS9XDWxadEHQjpedR6ECAqP4ijS8xNrlmcFrLYXysBlmwAPqhdbdh41GZfYPbxidnN1pSy+pv52VZZ1kq8V0peDJFljXNrW8S5Wl06S7gLAGBbto31SJjV10FKCyD7CjoHJxYGU/yESGSl3hYqkx5SV4JnyOY502PQjEq+eAMq9zotB+yy04g+FJo8IQq9EiMl9IKvaA7FERXUD8d00o8ZE43gt6e/vIAfD7G03udouHtQPzeG/LUPfN9RNApux+LtF0u50HeptOb0c49LrfTnFd6Nl7Y198NCWmT8ZozR3LwHG3LJEvy3a/xe+iTeX7NaVy2lPCJUMhqFL7wFqhh59NWgGqOOUqNx4Uq6lVq2fqMlF0XmK13qwOT69VMjCTM6GktcA7HgwmYpdLwVFClVHG0Rp40aT5TQI33nvix8Yxh3hdY=
  skip_cleanup: true

notifications:
  email:
    - tahtaciburak@gmail.com


