sudo: false
language: python
python:
  - '3.6'
env:
  global:
    - PACKAGE_NAME=ctwavelet
before_install:
  - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION
script:
  - python setup.py sdist bdist_wheel
  - pip install .
  - pip install pytest
  - pip install codecov
  - pytest tests/*
  - codecov
deploy:
  provider: pypi
  user: tahtaciburak
  distributions: sdist bdist_wheel
  password:
    secure: PHhopVZE+4XHWHrQ8NOMGpeY4+7MyKDp8ly1gZR5+/caSbxUr/WK4BKYdIxkN01rmp3Z+nWjB6XZyQqw8DtDTvQaZgKRn99r+NnZ5X5Y13aSM0RMMB7o5sxriRrzRdjwTnnJ7E9tYJ7zRn7hbKvIkaumX7U3v5qL4Uq/95Fe0S202c/lzAhZpRn3F4C7gqfFcD1MRVG8d9QhHsaRUC4SwYNl2LbnLmUcO1VvqUEK1ArSwb+ja9IjifbESn+El402LWtxWd1K9zsSuoGGpzUImOaoDvR31lvrRBLiyOTXr++/iPLP1k6llymnMQdBqzPYIfHyIU7kK1zHxQB2yeJsYbz/evBF1fxyCSZXvhq8QixXbowIDLFYyu6uvOgM4brSoALS8TaYOYOFjP3/WDK67W8gf/Tuu7uPC/4ZHdB8ZXrPMeUuoCOdH5VCBK4pRbboACHeM1VjgkFR3PHGuDdzrtrTUIUqJ/sQ4IXwUbhB2vwAZ8In8bgz5wPDPMDpPOKAiOqay6QY/AuXUSsUqPc5MT6XztjtqogsVoG4Dj00A+cEQlhlfz8HALI3tXYcENJoRaftc243aT5tkogIfM6aIJxGL7+54Lm+6e3maMCEB7YxdMx45AWVoAMPzGvn4Tj1UjYHuPdm8vjPbnNaMmLszaCwEuksCNBty+XPrwXB1Ug=
  skip_cleanup: true
  skip_existing: true
notifications:
  email:
  - tahtaciburak@gmail.com
